name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:

        # Récupérer le code source de l'application hébergé sur Github pour le rendre disponible pour Actions
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: release/2.0.0.0
        
        # Créer le fichier .env
      - name: 'Create env file'
        run: |
          touch .env
          echo DB_CONNECTION=mysql >> .env
          echo DB_HOST=172.16.47.178 >> .env
          echo DB_PORT=3306 >> .env
          echo DB_DATABASE=mydatabase >> .env
          echo DB_USERNAME=user >> .env
          echo DB_PASSWORD=password >> .env

        # Configurer l'environnement de build avec la bonne version de PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10'
          
      #- name: Install dependencies
        #run: composer install
        
      #- name: Run PHPUnit tests
        #run: vendor/bin/phpunit tests
      
      #- name: Run PHPStan static code analyse
        #run: vendor/bin/phpstan analyse fonction api tests views
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gyomada
          password: LGF8Q5zS$ymQ!4xK
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gyomada/transverse:v2
