name: CI Pipeline

on:
  push:
    branches:
      - main


env:
  DOCKERHUB_USERNAME: gyomada
  DOCKERHUB_PASSWORD: LGF8Q5zS$ymQ!4xK
  IMAGE_VERSION: $(date +%s)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code source de l'application hébergé sur Github pour le rendre disponible pour Actions
      - name: Checkout code
        uses: actions/checkout@v3

        # Configurer l'environnement de build avec la bonne version de PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10'
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gyomada
          password: LGF8Q5zS$ymQ!4xK
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gyomada/transverse:$(date +%s)
