name: CI Pipeline

on:
  push:
    branches:
      - main


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_VERSION: ${{ secrets.IMAGE_VERSION }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉  ${{ env.DOCKERHUB_USERNAME }} event."
      - run: echo "🎉  ${{ env.DOCKERHUB_PASSWORD }} event."
      - run: echo "🎉  ${{ env.IMAGE_VERSION }} event."
